export const wordsArrey = {
    fruits: {
        fruit: 'фрукт',
        apricot: 'абрикос',
        pineapple: 'ананас',
        banana: 'банан',
        bergamot: 'бергамот',
        grape: 'виноград',
        grapefruit: 'грейпфрут',
        pear: 'груша',
        melon: 'дыня',
        lemon: 'лимон',
        mandarin: 'мандарин',
        peach: 'персик',
        plum: 'слива',
        apple: 'яблоко',
        lime: 'лайм',
        kiwi: 'киви',
        fig: 'инжир',
        mango: 'манго',
        persimmon: 'хурма',
        pomelo: 'помело'
    },
    vegetables: {
        vegetable: 'овощ',
        basil: 'базилик',
        eggplant: 'баклажаны',
        bean: 'бобы',
        pea: 'горох',
        cabbage: 'капуста',
        potato: 'картофель',
        onion: 'лук',
        carrot: 'морковь',
        cucumber: 'огурец',
        pepper: 'перец',
        parsley: 'петрушка',
        tomato: 'помидор',
        radish: 'редис',
        beet: 'свекла',
        celery: 'сельдерей',
        pumpkin: 'тыква',
        dill: 'укроп',
        haricot: 'фасоль',
        garlic: 'чеснок',
        sorrel: 'щавель'
    },
    food: {
        food: 'питание, еда',
        ham: 'ветчина',
        sausage: 'колбаса, сосиска',
        meat: 'мясо',
        egg: 'яйцо',
        pizza: 'пицца',
        soup: 'суп',
        bread: 'хлеб',
        milk: 'молоко',
        porridge: 'каша',
        flour: 'мука',
        garlic: 'чеснок',
        salad: 'салат',
        fish: 'рыба',
        chicken: 'цыплёнок',
        pork: 'свинина',
        beef: 'говядина',
        steak: 'бифштекс, стейк',
        spice: 'специя, пряность',
        butter: 'масло',
        potato: 'картофель',
        macaroni: 'макароны',
        cheese: 'сыр',
        rice: 'рис',
        pasta: 'паста',
        ketchup: 'кетчуп',
        sauce: 'соус',
        mayonnaise: 'майонез',
        bean: 'фасоль',
        pepper: 'перец',
        salt: 'соль',
        sandwich: 'бутерброд',
        cutlet: 'котлета',
        caviar: 'икра',
        vegetables: 'овощи',
        fruit: 'фрукт',
        baked: 'печёный, выпеченный',
        fried: 'жареный',
        'pickled cucumbers': 'соленые огурцы',
        'marinated tomatoes': 'маринованные помидоры',
        tea: 'чай',
        coffee: 'кофе',
        cocoa: 'какао',
        chocolate: 'шоколад',
        jam: 'варенье; джем',
        sugar: 'сахар',
        candy: 'конфета',
        cake: 'кекс, торт',
        cookie: 'печенье',
        croissant: 'французский рогалик',
        cocktail: 'коктейль',
        juice: 'сок',
        jelly: 'желе',
        'ice cream': 'мороженое',
        pancake: 'блин, оладья',
        pie: 'пирог',
        sweet: 'сладкий (о вкусе)',
        bitter: 'горький (на вкус)',
        salted: 'солёный (о вкусе)',
        sour: 'кислый (на вкус)'
    },
    'The human body': {
        man: 'человек, мужчина',
        woman: 'женщина',
        body: 'тело',
        head: 'голова',
        shoulder: 'плечо',
        arm: 'рука',
        hand: 'рука (кисть)',
        elbow: 'локоть',
        chest: 'грудная клетка',
        stomach: 'живот, желудок',
        back: 'спина',
        bottom: 'зад',
        thigh: 'бедро',
        waist: 'талия',
        leg: 'нога',
        knee: 'колено',
        'calf calves': 'икра (икры ног)',
        'foot feet': 'ступня (ступни)',
        ankle: 'лодыжка',
        heel: 'пятка',
        thumb: 'большой палец',
        'ring finger': 'безымянный палец',
        'middle finger': 'средний палец',
        'index finger': 'указательный палец',
        'little finger': 'мизинец',
        fingernail: 'ноготь',
        shin: 'голень',
        toe: 'палец ноги',
        toenail: 'ноготь на пальце ноги',
        neck: 'шея',
        face: 'лицо',
        nose: 'нос',
        mouth: 'рот',
        'lip(s)': 'губа, губы',
        'tooth, teeth': 'зуб, зубы',
        tongue: 'язык',
        'eye(s)': 'глаз, глаза',
        eyebrow: 'бровь',
        eyelash: 'ресница',
        pupil: 'зрачок',
        eyelid: 'веко',
        chin: 'подбородок',
        cheek: 'щека',
        forehead: 'лоб',
        hair: 'волосы',
        hairy: 'волосатый',
        bald: 'лысый',
        moustache: 'усы',
        beard: 'борода'
    }
};